sudo: false
language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

before_install:
    - .travis/before_install.sh
    - export PATH=$PATH:$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin

install:
    - composer install

script:
    - php-cs-fixer fix --ansi --verbose --diff --dry-run
    - phpunit